[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jung-kurt/gofpdf"
  revision = "0298ebb7bb539ad17daadce86bedbdfd56c2bcd4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
